name: CI/CD with Jenkins

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Jenkins Pipeline
      env:
        JENKINS_USERNAME: ${{ secrets.JENKINS_USERNAME }}
        JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
      run: |
        curl -X POST https://fa87-59-96-56-57.ngrok-free.app/job/docker-pipeline/build \
          --user $JENKINS_USERNAME:$JENKINS_API_TOKEN
        # Add any additional curl options as needed
